{{- if ((.Values.containerization).rbac).create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $) | nindent 4 }}
  name: tonic-containerization
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "delete", "create", "watch", "deletecollection"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "delete", "create", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $) | nindent 4 }}
  name: tonic-containerization
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tonic-containerization
subjects:
- kind: ServiceAccount
  name: {{ template "tonic.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
