{{- $packerServiceAccount := ((.Values.containerization).datapacker).serviceAccount }}
{{- if $packerServiceAccount }}
{{- if and ($packerServiceAccount.create) ($packerServiceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $packerServiceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "tonic.labels" . | indent 4 }}
{{- if $packerServiceAccount.annotations }}
  annotations:
    {{- toYaml $packerServiceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}