{{- if .Values.tonicSsoConfig }}
{{- if .Values.tonicSsoConfig.googleAccountServiceJson }}
apiVersion: v1
kind: Secret
metadata:
  name: tonic-sso-google-account-service-json-secret
type: Opaque
data:
  secret: {{ .Values.tonicSsoConfig.googleAccountServiceJson | b64enc }}
{{- end }}
{{- end }}