{{- if .Values.tonicSmtpConfig }}
{{- if .Values.tonicSmtpConfig.smtpPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: tonic-smtp-password
type: Opaque
data:
  password: {{ .Values.tonicSmtpConfig.smtpPassword | b64enc }}
{{- end }}
{{- end }}