# use_ingress typically only used by TIM
{{- if (.Values.tonicai).use_ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tonic-web-server-ingress
  namespace: {{ .Release.Namespace }}
  {{- if ((.Values.tonicai).ingress).annotations }}
  annotations:
    {{- toYaml .Values.tonicai.ingress.annotations | nindent 4 }}
  {{- else }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/default-backend: "tonic-web-server"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600" # 1 hour
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600" # 1 hour
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # disable body size constraint
  {{- end }}
  {{- if .Values.tonicai.ingress.labels }}
  labels:
    {{- with .Values.tonicai.ingress.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.tonicai.ingress.class }}
  ingressClassName: {{ .Values.tonicai.ingress.class }}
  {{- end }}
  rules:    
  # Non-default SSL cert requires an FQDN.
  # - host: localhost
  #   http:
  #     paths:
  #       - path: /
  #         pathType: Prefix
  #         backend:
  #           service:
  #             name: tonic-web-server
  #             port:
  #               number: 443
  - http: #default
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: tonic-web-server
              port:
                number: 443
    {{- if (.Values.tonicai).ingress.host }}
    host: {{ .Values.tonicai.ingress.host }}
    {{- end }}
{{- end }}
