{{- if ((.Values.monitoring).podMonitors).create }}
{{- $matchValues := (list
  "structural-web-server"
  "structural-notifications"
  "structural-worker"
  "structural-data-packer"
)}}
{{- range $matchValue := $matchValues }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ $matchValue }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  labels:
    tonic.ai/metrics: {{ $matchValue }}
spec:
  podMetricsEndpoints:
    - port: metrics
      path: '/metrics'
  selector:
    matchLabels:
      tonic.ai/metrics: {{ $matchValue }}
---
{{- end }}
{{- end }}
