apiVersion: v1
kind: Service
metadata:
  labels:
    app: tonic-worker
  name: tonic-worker
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  - name: "4433"
    port: 4433
    targetPort: 443
  selector:
    app: tonic-worker
status:
  loadBalancer: {}
