{{- if .Values.dockerConfigAuth }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  name: {{ include "tonic.imagePullSecret.defaultName" $ }}
data:
  .dockerconfigjson: {{ .Values.dockerConfigAuth }}
type: kubernetes.io/dockerconfigjson
{{- end }}
