{{- $top := . }}
{{- $worker := deepCopy $top.Values.tonicai.worker | mustMerge (dict "name" "tonic-worker" "replicas" $.Values.numberOfWorkers) }}
{{- include "tonic.worker.deployment" (list $top $worker $top.Values.containerization) }}
