{{- $notifications := .Values.tonicai.notifications }}
{{- $ports := fromYaml (include "tonic.ports" (list $ $notifications.ports (dict "http" 7000 "https" 7001 "httpsOnly" false))) }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $ (dict "app" "tonic-notifications")) | nindent 4 }}
  name: tonic-notifications
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  {{- if not $ports.httpsOnly }}
  - name: {{ $ports.http | quote }}
    port: {{ $ports.http }}
    targetPort: http
  {{- end }}
  - name: {{ $ports.https | quote }}
    port: {{ $ports.https }}
    targetPort: https
  selector:
    app: tonic-notifications
status:
  loadBalancer: {}
