{{- $server := .Values.tonicai.web_server -}}
{{- $ports := fromYaml (include "tonic.ports" (list $ $server.ports (dict "httpsOnly" true)))  }}
{{- $annotations := dict }}
{{- if ((.Values.tonicai).web_server).annotations }}
{{- $annotations = .Values.tonicai.web_server.annotations }}
{{- else }}
{{- $annotations = (dict
    "service.beta.kubernetes.io/aws-load-balancer-internal" "true"
    "service.beta.kubernetes.io/aws-load-balancer-nlb-target-type" "ip"
    "service.beta.kubernetes.io/aws-load-balancer-scheme" "internal"
    "service.beta.kubernetes.io/aws-load-balancer-type" "nlb"
    "service.beta.kubernetes.io/azure-load-balancer-internal" "true"
)}}
{{- end }}
{{- $serviceType := include "tonic.web.serviceType" (list $) }}
apiVersion: v1
kind: Service
metadata:
  name: tonic-web-server
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "tonic.annotations" (list $ $annotations) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $ (dict "app" "tonic-web-server")) | nindent 4 }}
spec:
  ports:
  {{- if not $ports.httpsOnly }}
  - name: "http"
    port: 80
    targetPort: http
  {{- end }}
  - name: "https"
    port: 443
    targetPort: https
  type: {{ $serviceType }}
  selector:
    app: tonic-web-server
status:
  loadBalancer: {}
