{{- $workerPorts := .Values.tonicai.worker.workerPorts | default dict }}
{{- $httpsOnly := $workerPorts.httpsOnly | default false }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tonic-worker
  name: tonic-worker
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  {{- if not $httpsOnly }}
  - name: "8080"
    port: 8080
    targetPort: "http"
  {{- end }}
  - name: "4433"
    port: 4433
    targetPort: "https"
  selector:
    app: tonic-worker
status:
  loadBalancer: {}
