{{- $workerPorts := ((.Values.tonicai).worker).ports | default dict }}
{{- $httpsOnly := $workerPorts.httpsOnly | default true }}
{{- $httpPort := $workerPorts.http | default 2480 }}
{{- $httpsPort := $workerPorts.https | default 2467 }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $ (dict "app" "tonic-worker")) | nindent 4 }}
  name: tonic-worker
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  {{- if not $httpsOnly }}
  - name: "8080"
    port: 8080
    targetPort: {{ $httpPort }}
  {{- end }}
  - name: "4433"
    port: 4433
    targetPort: {{ $httpsPort }}
  selector:
    app: tonic-worker
status:
  loadBalancer: {}
