{{- if .Values.dockerConfigAuth }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  name: tonicai-build-writer-pull-secret
data:
  .dockerconfigjson: {{ .Values.dockerConfigAuth }}
type: kubernetes.io/dockerconfigjson
{{- end }}
