{{- $top := $ }}
{{- if (include "tonic.isNotificationsEnabled" $top) }}
{{- $notifications := $top.Values.tonicai.notifications }}
{{- $smtpConfig := $top.Values.tonicSmtpConfig }}
{{- if $smtpConfig }}
{{- if $smtpConfig.smtpPassword }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "tonic.annotations" (list $top) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $top) | nindent 4 }}
  name: tonic-smtp-password
type: Opaque
data:
  password: {{ $smtpConfig.smtpPassword | b64enc }}
{{- end }}
{{- end }}
{{- end }}
