apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: tonic-notifications
=======
  labels:
    app: tonic-notifications
>>>>>>> 3fcc1b5c09f483d144bbe7297e6b07dafb005058
  name: tonic-notifications
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "7000"
    port: 7000
<<<<<<< HEAD
    targetPort: 80
  - name: "7001"
    port: 7001
    targetPort: 443
  selector:
    io.kompose.service: tonic-notifications
=======
    targetPort: 7000
  - name: "7001"
    port: 7001
    targetPort: 7001
  selector:
    app: tonic-notifications
>>>>>>> 3fcc1b5c09f483d144bbe7297e6b07dafb005058
status:
  loadBalancer: {}
