{{- if eq (include "tonic.hostIntegration" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "tonic.allLabels" (list $) | nindent 4 }}
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  name: {{ .Values.tonicai.web_server.features.kubernetes_role | default "default" }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "pods/log", "deployments", "replicasets", "secrets"]
  verbs: ["get", "list", "patch", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "tonic.allLabels" (list $) | nindent 4 }}
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  name: role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.tonicai.web_server.features.kubernetes_role | default "default" }}
subjects:
- kind: ServiceAccount
  name: {{ template "tonic.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
