{{- $ports := ((.Values.tonicai).web_server).ports | default dict }}
{{- $httpsPort := $ports.https | default 6543 }}
apiVersion: v1
kind: Service
metadata:
  name: tonic-web-server
  namespace: {{ .Release.Namespace }}
{{- if  ((.Values.tonicai).web_server).annotations }}
  annotations:
    {{- toYaml .Values.tonicai.web_server.annotations | nindent 4 }}
{{- end }}

  labels:
    app: tonic-web-server
spec:
  ports:
  - name: "https"
    port: 443
    targetPort: {{ $httpsPort }}
# use_ingress currently only used by TIM
{{- if (.Values.tonicai).use_ingress }}
  type: ClusterIP
{{- else }}
  type: LoadBalancer
{{- end }}
  selector:
    app: tonic-web-server
status:
  loadBalancer: {}
