{{- $server := .Values.tonicai.web_server -}}
{{- if eq (include "tonic.web.separateBackgroundTasks" (list $ $server)) "separateBackgroundTasks" }}
{{- $ports := fromYaml (include "tonic.ports" (list $ $server.ports (dict "http" 6580 "https" 6543 "httpsOnly" true)))  }}
{{- $httpsOnly := $ports.httpsOnly }}
{{- $httpPort := $ports.http }}
{{- $httpsPort := $ports.https }}
{{- $appName := "tonic-task-runner" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $ (dict "app" $appName)) | nindent 4 }}
  name: {{ $appName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $appName }}
  strategy:
    type: {{ template "tonic.deployStrategy" . }}
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        {{- include "tonic.annotations" (list $) | nindent 8 }}
      labels:
        {{- include "tonic.allLabels" (list $ (dict "app" $appName)) | nindent 8 }}
    spec:
      nodeSelector:
        {{- include "tonic.nodeSelectors" (list $) | nindent 8 }}
      affinity:
        {{- include "tonic.affinity" (list $) | nindent 8 }}
      tolerations:
        {{- include "tonic.tolerations" (list $) | nindent 8 }}
      securityContext:
        {{- include "tonic.web.pod.securityContext" (list $) | nindent 8 }}
      initContainers:
        {{- include "tonic.initContainers" (list $ $server.initContainers) | nindent 8 }}
      containers:
      - securityContext:
          {{- include "tonic.web.container.securityContext" (list $ $server) | nindent 10 }}
        volumeMounts:
          {{- include "tonic.web.volumeMounts" (list $ $server) | nindent 10 }}
        env:
          {{- include "tonic.web.envVars" (list $ $server $httpsOnly $httpsPort $httpPort) | nindent 8 }}
        {{- if $server.envFrom }}
        envFrom:
        {{- with $server.envFrom }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        image: {{ include "tonic.web.container.image" (list $ $server) }}
        imagePullPolicy: Always
        name: {{ $appName }}
        ports:
          {{- include "tonic.web.ports" (list $ $httpsOnly $httpsPort $httpPort) | nindent 8 }}
        resources:
          {{- include "tonic.web.tasks.container.resources" (list $ $server) | nindent 10 }}
        startupProbe:
          {{- include "tonic.web.startupProbe" (list $ $httpsPort) | nindent 10 }}
      restartPolicy: Always
      serviceAccountName: {{ template "tonic.serviceAccountName" . }}
      imagePullSecrets:
      - name: {{ include "tonic.imagePullSecret.name" . }}
      volumes:
      {{- (include "tonic.web.volumes" (list $ $server)) | nindent 8 }}
{{- end }}
