{{- $worker := .Values.tonicai.worker }}
{{- $ports := fromYaml (include "tonic.ports" (list $ $worker.ports (dict "httpsOnly" true)))  }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $ (dict "app" "tonic-worker")) | nindent 4 }}
  name: tonic-worker
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  {{- if not $ports.httpsOnly }}
  - name: "8080"
    port: 8080
    targetPort: http
  {{- end }}
  - name: "4433"
    port: 4433
    targetPort: https
  selector:
    app: tonic-worker
status:
  loadBalancer: {}
