{{- if .Values.tonicai }}
{{- if .Values.tonicai.oracle_helper }}
{{- if .Values.tonicai.oracle_helper.version }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tonic-oracle-helper
  name: tonic-oracle-helper
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  - name: "5001"
    port: 5001
    targetPort: 5001
  selector:
    app: tonic-oracle-helper
status:
  loadBalancer: {}
{{- end }}
{{- end }}
{{- end }}