apiVersion: v1
kind: Service
metadata:
  name: tonic-web-server
  namespace: {{ .Release.Namespace }}
  annotations:
    # This annotation is only required if you are creating an internal facing ELB. Remove this annotation to create public facing ELB.
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
{{- end }}

  labels:
    app: tonic-web-server
spec:
  ports:
  - name: "https"
    port: 443
    targetPort: 443
  type: LoadBalancer
  selector:
    app: tonic-web-server
status:
  loadBalancer: {}
