{{- $top := $ }}
{{- $pullAuth := $top.Values.dockerConfigAuth }}
{{- if $pullAuth }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "tonic.annotations" (list $top) | nindent 4 }}
  name: {{ include "tonic.imagePullSecret.defaultName" $top }}
data:
  .dockerconfigjson: {{ $pullAuth }}
type: kubernetes.io/dockerconfigjson
{{- end }}
