{{- $top := $ }}
{{- if (include "tonic.isWebServerEnabled" $top) }}
{{- $ssoConfig := $top.Values.tonicSsoConfig }}
{{- if ($ssoConfig).googleAccountServiceJson }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "tonic.annotations" (list $top) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $top) | nindent 4 }}
  name: tonic-sso-google-account-service-json-secret
type: Opaque
data:
  secret: {{ $ssoConfig.googleAccountServiceJson | b64enc }}
{{- end }}
{{- end }}
