apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  name: tonic-pyml-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tonic.allLabels" (list $ (dict "app" "tonic-pyml-service")) | nindent 4 }}
spec:
  ports:
  - port: 7700
    targetPort: 7700
  selector:
    app: tonic-pyml-service
status:
  loadBalancer: {}
