apiVersion: v1
kind: Service
metadata:
  labels:
    app: tonic-notifications
  name: tonic-notifications
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  - name: "7001"
    port: 7001
    targetPort: 7001
  selector:
    app: tonic-notifications
status:
  loadBalancer: {}
