apiVersion: v1
kind: Service
metadata:
  name: tonic-web-server
  namespace: {{ .Release.Namespace }}
  annotations:
    # This annotation is only required if you are creating an internal facing ELB. Remove this annotation to create public facing ELB.
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: tonic-web-server
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  type: ClusterIP
  selector:
    app: tonic-web-server
