{{- if .Values.tonicSsoConfig }}
{{- if .Values.tonicSsoConfig.googleAccountServiceJson }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "tonic.annotations" (list $) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $) | nindent 4 }}
  name: tonic-sso-google-account-service-json-secret
type: Opaque
data:
  secret: {{ .Values.tonicSsoConfig.googleAccountServiceJson | b64enc }}
{{- end }}
{{- end }}
