{{- $top := $ }}
{{- if (include "tonic.isWebServerEnabled" $top) }}
{{- $license := $top.Values.tonicLicense }}
{{- if $license }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "tonic.annotations" (list $top) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $top) | nindent 4 }}
  name: tonic-license-secret
type: Opaque
data:
  license: {{ $license | b64enc }}
{{- end }}
{{- end }}
