
{{- if .Values.serviceAccount }}
{{- if .Values.serviceAccount.create }}
{{- $annotations := dict }}
{{- if .Values.serviceAccount.annotations }}
{{ $annotations = (merge $annotations .Values.serviceAccount.annotations) }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "tonic.annotations" (list $ $annotations) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $) | nindent 4 }}
  name: {{ template "tonic.serviceAccountName" . }}
{{- end }}
{{- end }}
