{{- $top := $ }}
{{- $dbConfig := $top.Values.tonicdb }}
{{- if $dbConfig.password }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "tonic.annotations" (list $top) | nindent 4 }}
  labels:
    {{- include "tonic.allLabels" (list $top) | nindent 4 }}
  name: tonic-db-password
type: Opaque
data:
  password: {{ $dbConfig.password | b64enc }}
{{- end }}
