{{- if .Values.tonicSsoConfig.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: tonic-sso-client-secret
type: Opaque
data:
  secret: {{ .Values.tonicSsoConfig.clientSecret | b64enc }}
{{- end }}